/** @type {import('tailwindcss').Config} */
export default {
	darkMode: ["class"],
	content: ["./src/**/*.{html,js,svelte,ts}"],
	theme: {
		extend: {
			colors: {
				primary: {
					DEFAULT: "#cc785c",
					active: "#a9583e",
					disabled: "#e6dfd8",
				},
				canvas: "#faf9f5",
				"surface-soft": "#f5f0e8",
				"surface-card": "#efe9de",
				"surface-cream-strong": "#e8e0d2",
				"surface-dark": "#181715",
				"surface-dark-elevated": "#252320",
				"surface-dark-soft": "#1f1e1b",
				ink: "#141413",
				"body-strong": "#252523",
				body: "#3d3d3a",
				muted: "#6c6a64",
				"muted-soft": "#8e8b82",
				"on-primary": "#ffffff",
				"on-dark": "#faf9f5",
				"on-dark-soft": "#a09d96",
				hairline: "#e6dfd8",
				"hairline-soft": "#ebe6df",
				"accent-teal": "#5db8a6",
				"accent-amber": "#e8a55a",
				success: "#5db872",
				warning: "#d4a017",
				error: "#c64545",
			},
			fontFamily: {
				display: ["Cormorant Garamond", "Tiempos Headline", "Garamond", "serif"],
				sans: ["Inter", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "Roboto", "sans-serif"],
				mono: ["JetBrains Mono", "ui-monospace", "monospace"],
			},
			fontSize: {
				"display-xl": ["64px", { lineHeight: "1.05", letterSpacing: "-0.02em" }],
				"display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em" }],
				"display-md": ["36px", { lineHeight: "1.15", letterSpacing: "-0.015em" }],
				"display-sm": ["28px", { lineHeight: "1.2", letterSpacing: "-0.01em" }],
				"title-lg": ["22px", { lineHeight: "1.3" }],
				"title-md": ["18px", { lineHeight: "1.4" }],
				"title-sm": ["16px", { lineHeight: "1.4" }],
				"body-md": ["16px", { lineHeight: "1.55" }],
				"body-sm": ["14px", { lineHeight: "1.55" }],
				caption: ["13px", { lineHeight: "1.4" }],
				"caption-upper": ["12px", { lineHeight: "1.4", letterSpacing: "0.1em" }],
			},
			spacing: {
				section: "96px",
				xxl: "48px",
				xl: "32px",
				lg: "24px",
				md: "16px",
				sm: "12px",
				xs: "8px",
				xxs: "4px",
			},
			borderRadius: {
				xs: "4px",
				sm: "6px",
				md: "8px",
				lg: "12px",
				xl: "16px",
				pill: "9999px",
				full: "9999px",
			},
			boxShadow: {
				soft: "0 1px 3px rgba(20, 20, 19, 0.08)",
				card: "0 4px 20px rgba(20, 20, 19, 0.06)",
				elevated: "0 8px 30px rgba(20, 20, 19, 0.12)",
			},
		},
	},
	plugins: [require("tailwindcss-animate")],
};
